#!/bin/python3
import math
import os
import random
import re
import sys

# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.

def diagonalDifference(arr):
    # Write your code here
    sum_1=sum_2=0
    for i in range(0,n):
        for j in range(0,n):
            if(i==j):
                sum_1+=arr[i][j]
    for i in range(0,n):
        for j in range(0,n):
            if(i+j==n-1):
                sum_2+=arr[i][j]
    diff=sum_1-sum_2
    return(abs(diff))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
    n = int(input().strip())
    arr = []
    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))
    result = diagonalDifference(arr)
    print(result)
