#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'lonelyinteger' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def lonelyinteger(arr):
    # Write your code here
    arr.sort()
    print(arr)
    if len(arr)<3:
        return arr[0]
    elif arr[0]!=arr[1]:
        return arr[0]
    else:
        return lonelyinteger(arr[2:])

if __name__ == '__main__':
    n = int(input().strip())
    arr = list(map(int, input().rstrip().split()))
    result = lonelyinteger(a)
    print(result)
